import { Pathway_Extreme } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AlertMessage from "@/components/alertmessage/AlertMessage";

const pathway = Pathway_Extreme({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="impact-site-verification" content="96a6a1b9-e6ac-4ae5-a7f1-fbc8efbacd19" />
      </head>
      <body className={pathway.className}>
        <AlertMessage />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
